trigger:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: 
- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 
- '*'

pr:
- '*'

jobs:
- job: ListSnapshotsAndExportToCSV
  displayName: 'List Snapshots and Export to CSV'
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: AzureCLI@2
      displayName: 'Azure Login'
      inputs:
        azureSubscription: $(6f79126d-0f7b-4f16-915a-b0f1125bbe4f)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az login --service-principal --username $(0c52b427-5dc8-4de0-b2aa-e1bdfb2a5602) --password $(Gc98Q~hwwTl2qGL6p9c9mnGommV5PbbQ~GO6.doG) --tenant $(6f79126d-0f7b-4f16-915a-b0f1125bbe4f) 

    - task: AzureCLI@2
      displayName: 'List Snapshots'
      inputs:
        azureSubscription: $(6f79126d-0f7b-4f16-915a-b0f1125bbe4f)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az snapshot list --query "[].{Name:name, ResourceGroup:resourceGroup, CreationDate:timeCreated}" --output table > snapshots.txt

    - script: |
        python3 -c "import csv

        with open('snapshots.txt', 'r') as file:
            data = [line.strip().split() for line in file]

        with open('snapshots.csv', mode='w', newline='') as csv_file:
            csv_writer = csv.writer(csv_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            csv_writer.writerow(['Name', 'ResourceGroup', 'CreationDate'])
            for row in data:
                csv_writer.writerow(row)"
      displayName: 'Export to CSV'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'snapshots'
